### ISSUE TITLE
KEGG pathway diagram does not show up in iDEP 0.92

### ISSUE THREAD

**Issue by gexijin** [iDEP-SDSU/idep#119]
Keeps getting errors using the 0.92 version of the database.

**Comment by mgalland** [comment]
Hello @gexijin 
I must say that I cannot get the KEGG pathway to work in my own hands. 

For instance, the "glucosinolate pathway" is enriched in my list of differential genes (see attached) but I cannot display it...
![Screenshot 2022-02-25 at 15 57 29](https://user-images.githubusercontent.com/10114186/155736916-f9819c8e-aaac-4643-ab2d-3c538205d23b.png)

I love the application and I will definitely use it and cite it in my own lessons. Together with other scientists at the University of Amsterdam, we have developed a [lesson](https://scienceparkstudygroup.github.io/rna-seq-lesson/) on RNA-seq and your tool will be a very good addition to our section on enrichment analyses. Very complete thanks!

Hope you can help me!
Thanks
Marc

[list_of_diff_genes.txt](https://github.com/iDEP-SDSU/idep/files/8142069/list_of_diff_genes.txt)
