### ISSUE TITLE
Give access to the last version of the database

### ISSUE THREAD

**Issue by Akusem** [iDEP-SDSU/idep#130]
Hi,
I have setup a local version of iDEP after many try, but I have only access data92, a 2 years old version of the database, as the install instruction haven't been updated for the last 2 years.

I have seen in iDEP93 that you are now at the data103 version of the db.

Do you plan to allow user to download the last version of the database ? And if yes, where ?

**Comment by EricTulowetzke** [comment]
Hi,

We are currently working on producing instructions to install a local version of data103. Is there anything else we can help you with?

Also if you have more feedback please come to the open forum this Friday at 2 pm (US central time) June 18th(link is also on iDEP page)

https://sdstate.zoom.us/j/94066063700

**Comment by Akusem** [comment]
Hi,
Thank you for the fast answer.

> Is there anything else we can help you with?

For my use case, I have added a new species (Phaeodactylum tricornutum) using a GMT file with GO data, is it all I have to do ? Or do I need to add other files to the db to have a good support of this species, notably for the enrichment in DEG2 tab ? 

Finally, not only for me, but updating the installation instruction is really needed as they are not working/have missing step, I simply can't reliably install iDEP currently :( 

> Also if you have more feedback please come to the open forum this Friday at 2 pm (US central time) June 18th(link is also on iDEP page)
Thanks for the head up, I will be there.

**Comment by gexijin** [comment]
Latest version is now available. https://github.com/iDEP-SDSU/idep#readme
Thanks for your feedback.
