### ISSUE TITLE
Update install instruction

### ISSUE THREAD

**Issue by Akusem** [iDEP-SDSU/idep#132]
Hi,
The installation instructions haven't been updated since two years, and more importantly, present some errors, missing files and instructions. Now that development and database update of iDEP has been financed, an update and fix of the README concerning the installation would be greatly appreciated.

While trying to install iDEP on my laptop, I have encounter many errors/confusing parts in the installation instructions. 
I wasn't able to install it locally (but R being R, I'm more reproaching it to R and it's dependencies incompatibilities, when you have one R version for all your tools), but I build successfully one time (and only one time) a working Docker version. 

While waiting for an update on the documentation, here some notes that I have about the current Docker installation instructions:

-  The download links to the database still download a 2 years old version of the database, with a missing file (`STRING11_species.csv` as described in #103). I have opened an issue (#130) about it. For now, to bypass the missing file problem, follow the instructions of #103.
- The instruction should start from step 2. Step one is redundant, and can introduce bug I think. Or at least, precise explicitly that they are independent way of installation.
- The nginx service crash, I'm not sure how to fix it, so for now I put it in comment in the docker-compose.
- There is a missing step, before launching the docker (after step 2). You have to open `shinyapps/idep93/server.R` and modify the var `datapath` to the path to the data folder. When using Docker-compose it's `/srv/data/`. Note, use the last version of iDEP, here it's idep93.
- Without the nginx service, I have to replace in docker-compose the `expose 3838` for iDEP service by `ports: -"3838:3838"`

**Comment by gexijin** [comment]
We recently updated the database and also instructions. Please see the readme file. https://github.com/iDEP-SDSU/idep#readme
