### ISSUE TITLE
Atlantic Salmon Ensembl?

### ISSUE THREAD

**Issue by marwa38** [iDEP-SDSU/idep#140]
Hello 

Could you please let me know if you are working on implementing Atlantic Salmon from Ensembl: https://rapid.ensembl.org/Salmo_salar_GCA_905237065.2/Info/Index

Thanks

**Comment by gexijin** [comment]
Thanks for your question. If Atlantic salmon will be included in Ensembl genomes, we will incorporate it. 
We will soon have time to figure out ways to include customize genome. Hopefully in the next few months.

**Comment by marwa38** [comment]
Atlantic salmon genome is already on Ensembl since a long time. 
 The one I shared is the latest Ensembl release. 
 Thanks for letting me know,  Hopefully soon. 
 Anyway to upload it from my side and work on iDEP analysis currently?
 Cheers

**Comment by gexijin** [comment]
The genome assembly we have in iDEP is ICSASG_v2.
This is Ensembl release 104. 
We update at least once a year.
Gene IDs look like this:
ENSSSAG00000000105
ENSSSAG00000000106
ENSSSAG00000000107
ENSSSAG00000000107
ENSSSAG00000000108
ENSSSAG00000000109
ENSSSAG00000000109
ENSSSAG00000000110
ENSSSAG00000000111
ENSSSAG00000000111
ENSSSAG00000000112
ENSSSAG00000000113
ENSSSAG00000000113
ENSSSAG00000000114
ENSSSAG00000000114
ENSSSAG00000000115
ENSSSAG00000000116

**Comment by marwa38** [comment]
Thanks very much again, Steven @gexijin 

Just to let you know that my samples aligned to release 104 worked well on the new version ( iDEP94). 
Could you please let me know when will you plan to allow the customize genome option?
If not soon, hopefully, the time to update the genome is approaching so that there is a possibility to include this rapid release from Ensembl?
https://rapid.ensembl.org/Salmo_salar_GCA_905237065.2/Info/Index

**Comment by gexijin** [comment]
Thanks for the update. Yesterday I uploaded new annotation data to idep95 and shinygo75. Take a look and see if it still works and if the genome has been updated. Thanks.

**Comment by marwa38** [comment]
Thanks very much, Steven @gexijin
I confirm that the new iDEP 95 worked well when I uploaded the release 104 counts table. 
I have another table that it would be so helpful to work within iDEP 95 but it is aligned not to Ensembl release 104 of Atlantic Salmon but to the Ensembl rapid release (Atlantic Salmon)

I was wondering if there is a possibility to update the Ensembl with the light-weighted rapid releases as they contain more annotations? http://ftp.ensembl.org/pub/rapid-release/species/Salmo_salar/
