### ISSUE TITLE
Which method is used, either limma or DESeq2?

### ISSUE THREAD

**Issue by wonwill** [iDEP-SDSU/idep#148]
Is it possible to know which method is used for my DEG analysis, either limma or DESeq2?

I got the DEG list (A vs B) from only two groups (A and B), but the list was different from the one that was calculated from four groups (A, B, C, D).

I guest that limma and DESeq2 would be used for two and four groups, respectively. Am I right?

**Comment by gexijin** [comment]
If you uploaded read counts data, you can choose either DESeq2 or limma in the DEG1 tab. 
If you uploaded normalized expression data, by default limma is used. 
Thank you for the question. To get prompt answers to these types of questions please email us directly at gelabinfo@gmail.com
