### ISSUE TITLE
I have a problem about pathwayDB!

### ISSUE THREAD

**Issue by luozhy88** [iDEP-SDSU/idep#160]
![image](https://user-images.githubusercontent.com/94740863/142723840-a80bc663-cc7a-4a66-a2bd-6f09723dba31.png)![image](https://user-images.githubusercontent.com/94740863/142723889-7f5ce5ec-69b9-494d-b91f-2780a6ab1d26.png)Hi，I have a problem about pathwayDB!
I can not unzip all the pathwayDB!

**Comment by tawaya** [comment]
I have the same issue.
$ wget http://18.235.92.206:8080/pathwayDB.tar.gz
$ tar -zxvf pathwayDB.tar.gz

the last 2 lines reported by -v option says
x pathwayDB/Northern American deer mouse__pmbairdii_gene_ensembl.db: truncated gzip input
tar: Error exit delayed from previous errors.

**Comment by gexijin** [comment]
We updated the database. I think this is resolved.
