### ISSUE TITLE
TPM?

### ISSUE THREAD

**Issue by AgatioDev** [iDEP-SDSU/idep#161]
Dear idep team,
thx for your nice tool for wet biologist such as me :) 

I am wondering if it will be possible to obtain "TPM" (transcript per million)? 
(or maybe in a near future?)

**Comment by gexijin** [comment]
Thank you for this suggestion. We will add this functionality in the new version. We are rewriting iDEP from scratch here; https://github.com/espors/idepGolem   I will move this issue here.

**Comment by gexijin** [comment]
I moved this issue there: https://github.com/espors/idepGolem/issues/63
