### ISSUE TITLE
data dir not correct

### ISSUE THREAD

**Issue by daaaaande** [iDEP-SDSU/idep#164]
dear devs, it seems like the current version depicts data104/ as the data dir in the provided screenshots, Yet the current R server.R looks for the data in ../../data104b/. This leads to the Shiny application crashing. am i doing something wrong here?

Cheers!

**Comment by gexijin** [comment]
iDEP 0.94 uses data104/, while iDEP 0.95 uses data104b/.   Please start the Shiny app in different folders. 
Thank you for the feedback.
