### ISSUE TITLE
[BUG] High resolution figure download button not working in PCA > Pathway Analysis of PCA rotation

### ISSUE THREAD

**Issue by Akusem** [iDEP-SDSU/idep#166]
Hi, 

We just discovered that the download in high resolution button for the Pathway Analysis of PCA rotation doesn't seem to work

It's the `High resolution figure` button on the PCA panel here:

![image](https://user-images.githubusercontent.com/24433720/155555132-4ca738c1-14a8-4849-a396-11d32e77ec66.png)

Also, do you think it could be improved to allow download of the figure in a vectorial format, like EPS for example ? 
I imagine the library used to create the graph need to be compatible, but if it's the case, it could be a nice feature to have.

**Comment by gexijin** [comment]
Thank you for pointing this out. It is caused by the error "figure margin too big". It was solved by increasing the width of the plot. The downloaded EPS file is vector graphics.
