### ISSUE TITLE
KEGG pathway not being displayed

### ISSUE THREAD

**Issue by mgalland** [iDEP-SDSU/idep#167]
Hello @gexijin 
I must say that I cannot get the KEGG pathway to work in my own hands. 

For instance, the "glucosinolate pathway" is enriched in my list of differential genes (see attached) but I cannot display it...
![Screenshot 2022-02-25 at 15 57 29](https://user-images.githubusercontent.com/10114186/155736916-f9819c8e-aaac-4643-ab2d-3c538205d23b.png)

I love the application and I will definitely use it and cite it in my own lessons. Together with other scientists at the University of Amsterdam, we have developed a [lesson](https://scienceparkstudygroup.github.io/rna-seq-lesson/) on RNA-seq and your tool will be a very good addition to our section on enrichment analyses. Very complete thanks!

Hope you can help me!
Thanks
Marc

[list_of_diff_genes.txt](https://github.com/iDEP-SDSU/idep/files/8142069/list_of_diff_genes.txt)

_Originally posted by @mgalland in https://github.com/iDEP-SDSU/idep/issues/119#issuecomment-1050929672_

**Comment by gexijin** [comment]
Hi Marc, I will take a look. Thank you for using our tool.

**Comment by gexijin** [comment]
Hi Marc, 
This issue is fixed. The problem is caused by a function keggConv, for somereason, is not loaded. It is solved when I changed it to KEGGREST::keggConv.    I also solved another issue that caused the rendering to be slow.  
Your online lesson is so comprehensive. I will study it myslef.  Do you have any suggestions for iDEP and ShinyGO?

**Comment by gexijin** [comment]
Your gene list is rather unsually large, ~5000 genes. I typically like to bring the size down to less than 2000.

**Comment by gexijin** [comment]
I tweeted about your lesson and 72 likes and 168 link clicks so far: https://twitter.com/StevenXGe/status/1497296090881744897

**Comment by mgalland** [comment]
Thanks for being so responsive! Works like a charm. Thanks for the quick fix.
Yes, the list was quite long but it's based on the lesson example that gives indeed a lot of diff. genes...Normally I have less diff. genes of course. 
I will update the lesson to incorporate your great tool, it is much easier to use than the clusterProfilter.
Cheers
Marc
