### ISSUE TITLE
Access to database 105 (iDEP 95 db)

### ISSUE THREAD

**Issue by Akusem** [iDEP-SDSU/idep#170]
Hi,
I'm currently upgrading our [instance](https://idep.diatomicsbase.bio.ens.psl.eu/) from iDEP 94 to 95, notably to have access to some species from Ensembl Protists, but if I'm not mistaken, it seems that the [download link](http://18.235.92.206:8080/) for the database in the readme point toward data104, the database of iDEP 94 and not from the last version, iDEP 95.

Do you plan to release iDEP 95 database like it was the case for iDEP 94 with data104 ?

**Comment by gexijin** [comment]
New database is now uploaded. Please go to the same linke. Thanks for using our software.
