### ISSUE TITLE
What is "c.out"?

### ISSUE THREAD

**Issue by repbio** [iDEP-SDSU/idep#197]
Hi,
I have a problem with the object "c.out" in iDEP_core_functions.R. When I try to run "selectedHeatmap.data()", it gives an error, which says, "object 'c.out' not found." What is "c.out"? It comes up twice in the iDEP_core_functions.R, but I cannot find where it is defined. Could you help me out with this?

<img width="605" alt="image" src="https://user-images.githubusercontent.com/105068884/167171201-f5bec238-7962-40af-9c05-7fde4bb4bb64.png">

Thanks,

**Comment by EricTulowetzke** [comment]
@repbio hello and sorry for the delay.

I just started working on this project again as a side project.

The last year we have worked on a refactor of iDEP into an R shiny package. So you will be able to install the package locally from GitHub.

It will be publicly Available soon in the next week. I will message you the new repo when it is ready.
