### ISSUE TITLE
Running in Docker

### ISSUE THREAD

**Issue by MLKaufman** [iDEP-SDSU/idep#24]
Running these commands, nginx fails to run with the following output.  Is there a problem with the nginx configuration file? I have not modified any of the files, only ran the following.  Thanks!

> git clone https://github.com/iDEP-SDSU/idep.git
The following command starts containers from docker-compose.yml. The R server listening for HTTP connections on port 3838
> docker-compose up -d

Gives this output:

`C:\Users\mikel\idep\idep (master -> origin)
λ docker-compose.exe up
Starting idep_webapp_1 ... done
Starting idep_nginx_1 ... done
Attaching to idep_webapp_1, idep_nginx_1
webapp_1  | [2018-02-14 20:43:52.043] [INFO] shiny-server - Shiny Server v1.5.7.877 (Node.js v6.10.3)
webapp_1  | [2018-02-14 20:43:52.048] [INFO] shiny-server - Using config file "/etc/shiny-server/shiny-server.conf"
nginx_1   | 2018/02/14 20:43:52 [emerg] 1#1: host not found in upstream "idep_webapp_2:3838" in /etc/nginx/nginx.conf:19
webapp_1  | [2018-02-14 20:43:52.104] [WARN] shiny-server - Running as root unnecessarily is a security risk! You could be running more securely as non-root.
nginx_1   | nginx: [emerg] host not found in upstream "idep_webapp_2:3838" in /etc/nginx/nginx.conf:19
webapp_1  | [2018-02-14 20:43:52.121] [INFO] shiny-server - Starting listener on 0.0.0.0:3838
idep_nginx_1 exited with code 1`

**Comment by kruny1001** [comment]
The standalone version of iDEP is not available yet. Database is quite huge(60GB plus 20GB) at this time and we don't offer the data as open source at this point. I am sorry to tell you. Does http://bioinformatics.sdstate.edu/idep/ not work for you? If you have a trouble with idep online version. Let me know.

**Comment by MLKaufman** [comment]
Thanks for writing back! For the most part the website works. When using the example dataset it works great. When I upload larger datasets to analyze it seems to crash. Wanted to have it running locally for better performance.

**Comment by kruny1001** [comment]
@MLKaufman Can I ask you how big is your data?

**Comment by MLKaufman** [comment]
The uploaded CSV file is about 11mb.  The dataset has 31,000 genes and 62 samples.  Definitely larger than average.

**Comment by kruny1001** [comment]
Current iDEP setting allows up to 200MB. That might be the number of samples. Why don't you reduce the sample size to 5 or 6 for testing. Does data is public? or security sensitive? If you can share me the data file, I may look into it.

**Comment by MLKaufman** [comment]
It actually initially loads fine.  I think some of the submodules just can't handle that many genes/samples.

**Comment by kruny1001** [comment]
We are investgating this issue. We will let you know when this issue is resolved
