### ISSUE TITLE
customary R codes can't be downloaded.

### ISSUE THREAD

**Issue by yeroslaviz** [iDEP-SDSU/idep#25]
Hi,
when I try to download the customary R code from the iDEP server I get the following error - 

`ERROR: An error has occurred. Check your logs or contact the app author for clarification.`

The link for the download is this:
http://bioinformatics.sdstate.edu/idep/session/6bd2ddca1847866ef426d7810fb29f75/download/downloadRcodeMarkdown?w=

is it correct?

thanks
Assa

**Comment by gexijin** [comment]
We have a new version of iDEP.
