### ISSUE TITLE
Limma voom issue in Rmd

### ISSUE THREAD

**Issue by tovahmarkowitz** [iDEP-SDSU/idep#65]
Related to #42.

Although the updates for limma voom now work on the website, these changes were not incorporated into iDEP_core_functions.R. Please adjust.

**Comment by gexijin** [comment]
Hi Tovah,
We are completely rewriting iDEP to be modular and the same code are used by the Shiny app and Rmarkdown. So it might not be our priority to change the iDEP Core functions.
